IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'FoodStock'))
BEGIN
    CREATE TABLE dbo.FoodStock
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name nvarchar(200) NOT NULL,
	Number int NOT NULL
	)  ON [PRIMARY]
	ALTER TABLE dbo.FoodStock ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END